fruits = ["Apple","Banana","Cherry","Guava","Orange"]
print("The length of the list is", len(fruits))
print("The list contains:", fruits)
print("The first element is:", fruits[0])
print("The last element is", fruits[-1])
fruits.append("Strawberry")
print("The updated list is:", fruits)
fruits.remove("Banana")
print("The updated list is:", fruits)
fruits.sort()
print("The sorted list is:", fruits)
fruits.pop(1)
print("The updated list is:", fruits)
fruits.reverse()
print("The reversed list is:", fruits)
print(fruits*3)
print(fruits[1:4])
fruits.clear()
print("The cleared list is:", fruits)